### ISSUE TITLE
Incomplete requirements

### ISSUE THREAD

**Issue by deklanw** [paulbricman/autocards#19]
Had to `pip install` both `sentencepiece` and `protobuf` to get example working

**Comment by thiswillbeyourgithub** [comment]
What example are you talking about? I don't seem to have any issue with that.

**Comment by deklanw** [comment]
@thiswillbeyourgithub The example from the README. Try in a fresh e.g. conda environment.

Also, you added `tika` as well without adding to requirements

https://github.com/paulbricman/autocards/commit/4e32040c623eb0855dd9049c7380839de36e95fd#diff-6f5fe3463e002ee0be164405bc542a7e7cf766983f1a230569b6c8b080648541R14
