### ISSUE TITLE
Limited number of flashcards generated despite large input

### ISSUE THREAD

**Issue by paulbricman** [paulbricman/autocards#2]
> Ya, I did the 'open demo' and i put in a good couple of paragraphs of content. It never generated more than3 questions. 😬

It might be useful to feed individual paragraphs in the thing. This way, the question answering check has a better chance of succeeding, because it won't find answers in other places and invalidate the flashcard candidate.

**Comment by thiswillbeyourgithub** [comment]
Autocards supports dividing input into paragraphs.
