### ISSUE TITLE
ERROR - You need to have sentencepiece installed to convert a slow tokenizer to a fast one

### ISSUE THREAD

**Issue by xoraus** [paulbricman/autocards#35]
Facing issue after executing this "a = Autocards(in_lang="en", out_lang="en")"

ValueError: Couldn't instantiate the backend tokenizer from one of: 

(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.

I tried this: https://stackoverflow.com/questions/65431837/transformers-v4-x-convert-slow-tokenizer-to-fast-tokenizer this solution but it still did not work.

According to Transformers v4.0.0 [release](https://github.com/huggingface/transformers/releases/tag/v4.0.0), sentencepiece was removed as a required dependency. This means that "The tokenizers that depend on the SentencePiece library will not be available with a standard transformers installation" including the XLMRobertaTokenizer. However, sentencepiece can be installed as an extra dependency.

**Comment by thiswillbeyourgithub** [comment]
Have you tried removing the "in_lang" and "out_lang" arguments ? Not sure that it helps but that's a start. Those arguments are not supposed to be used for english as it's the default IIRC.

**Comment by aforank** [comment]
> 

Still does not work

**Comment by thiswillbeyourgithub** [comment]
Please try this and report back:
https://github.com/patil-suraj/question_generation/issues/53

**Comment by aforank** [comment]
I tried installing additional packages and it seems to be working fine post that. Here are the list of commands we need to run

`pip install sentencepiece`
`pip install protobuf==3.20.1`
`pip install lxml`
