### ISSUE TITLE
Ignore references while consuming test

### ISSUE THREAD

**Issue by paulbricman** [paulbricman/autocards#4]
> I've been trying out random wiki pages... Having references [1] etc seems to mess it up.. as well as the line break etc. I've been putting them in word, Replacing "^ p " (paragraph) to ". " As well, for quotes you can search "[ ^ # ]" which ^ # is any number...

Sounds like a nice possible option, ignore_references as an option of the consume functions or something.

**Comment by thiswillbeyourgithub** [comment]
This has been implemented as well.
