### ISSUE TITLE
Update the README with instructions for running it, overview of options

### ISSUE THREAD

**Issue by paulbricman** [paulbricman/autocards#5]

**Comment by bjsi** [comment]
My notes from installing:

One of the packages requres the rust compiler so you need to install rust. On linux this is pretty easy just follow the requirements [here](https://www.rust-lang.org/tools/install). On Windows I think you also need to have the [Microsoft C++ build tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/).

For the required Python packages, here's what I ended up running:

pip install -U transformers==3.0.0 --quiet
pip install nltk
python -m nltk.downloader punkt
pip install torch
pip install bs4
