### ISSUE TITLE
Support other Language?

### ISSUE THREAD

**Issue by DimIsaev** [paulbricman/autocards#9]
Example russian language?
Thanks

**Comment by uuuser-name** [comment]
Same request, it might be useful to add the possibility to use other datasets/models, for the few well supported languages they may exist in.

**Comment by thiswillbeyourgithub** [comment]
Same here, amusingly the default works model works fine on french but outputs in english.

I don't know if there are model that have been trained for question answering in other languages, the keywords you want to use is "qa" there : https://huggingface.co/models

**Comment by thiswillbeyourgithub** [comment]
Sorry for the duplicated notification but I think it is important.

@paulbricman would you mind sharing with us how you settled on which model to use? I'd like to use the same heuristics as you to see if there are other model that could be use, be it in other languages or (crucially) on specific topics like medical stuff.

Some light on the subject would go a long way :)

Thanks!

**Comment by paulbricman** [comment]
I used models related to the ones from the forked repo, just different sizes. I think he mentions some others in there, so have a look there! My heuristics were just flashcard quality, quantity, and how long it takes to generate them.

**Comment by thiswillbeyourgithub** [comment]
I added support for automatic on the fly translation in my latest commit. So the model used for question generation is still the original one as it was trained on a specific dataset (SQuAD) and it is not feasible to retrain the model for every language. Input text is just translated to english if needed and output is translated from english to whatever else the user wants.
